set(_AMENT_PACKAGE_NAME "fr_lio")
set(fr_lio_VERSION "0.1.0")
set(fr_lio_MAINTAINER "Alvaro J. Gaona <alvgaona@gmail.com>")
set(fr_lio_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "sensor_msgs" "std_srvs" "visualization_msgs" "common_interfaces" "tf2" "pcl_ros" "pcl_conversions" "livox_ros_driver2")
set(fr_lio_BUILDTOOL_DEPENDS "ament_cmake")
set(fr_lio_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "sensor_msgs" "std_srvs" "visualization_msgs" "common_interfaces" "tf2" "pcl_ros" "pcl_conversions" "livox_ros_driver2")
set(fr_lio_BUILDTOOL_EXPORT_DEPENDS )
set(fr_lio_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "rclcpp_components" "std_msgs" "sensor_msgs" "std_srvs" "visualization_msgs" "common_interfaces" "tf2" "pcl_ros" "pcl_conversions" "livox_ros_driver2")
set(fr_lio_TEST_DEPENDS "ament_cmake_gtest")
set(fr_lio_GROUP_DEPENDS )
set(fr_lio_MEMBER_OF_GROUPS )
set(fr_lio_DEPRECATED "")
set(fr_lio_EXPORT_TAGS)
list(APPEND fr_lio_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
