set(_AMENT_PACKAGE_NAME "traj_utils")
set(traj_utils_VERSION "0.0.0")
set(traj_utils_MAINTAINER "ma <ma@todo.todo>")
set(traj_utils_BUILD_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "visualization_msgs" "builtin_interfaces" "rosidl_default_generators" "PCL" "Eigen3")
set(traj_utils_BUILDTOOL_DEPENDS "ament_cmake")
set(traj_utils_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "visualization_msgs" "builtin_interfaces" "rosidl_default_generators" "PCL" "Eigen3")
set(traj_utils_BUILDTOOL_EXPORT_DEPENDS )
set(traj_utils_EXEC_DEPENDS "rclcpp" "std_msgs" "geometry_msgs" "visualization_msgs" "builtin_interfaces" "rosidl_default_generators" "PCL" "Eigen3")
set(traj_utils_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(traj_utils_GROUP_DEPENDS )
set(traj_utils_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(traj_utils_DEPRECATED "")
set(traj_utils_EXPORT_TAGS)
list(APPEND traj_utils_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
