set(_AMENT_PACKAGE_NAME "quadrotor_msgs")
set(quadrotor_msgs_VERSION "0.0.0")
set(quadrotor_msgs_MAINTAINER "ma <ma@todo.todo>")
set(quadrotor_msgs_BUILD_DEPENDS "Eigen3" "rclcpp" "rosidl_default_generators" "geometry_msgs" "nav_msgs" "std_msgs")
set(quadrotor_msgs_BUILDTOOL_DEPENDS "ament_cmake")
set(quadrotor_msgs_BUILD_EXPORT_DEPENDS "rclcpp" "rosidl_default_generators" "geometry_msgs" "nav_msgs" "std_msgs")
set(quadrotor_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(quadrotor_msgs_EXEC_DEPENDS "Eigen3" "rclcpp" "rosidl_default_generators" "geometry_msgs" "nav_msgs" "std_msgs")
set(quadrotor_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(quadrotor_msgs_GROUP_DEPENDS )
set(quadrotor_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(quadrotor_msgs_DEPRECATED "")
set(quadrotor_msgs_EXPORT_TAGS)
list(APPEND quadrotor_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
