/fastlio_mavros_odometry_bridge:
  ros__parameters:
    attitude_yaw_offset_rad: 0.0
    body_yaw_offset_rad: 0.0
    child_frame_id: body
    default_angular_velocity_variance: 0.02
    default_linear_velocity_variance: 0.01
    default_orientation_variance: 0.02
    default_position_variance: 0.01
    derive_missing_twist: false
    enforce_unique_ev_input: true
    force_frame_ids: false
    frame_id: camera_init
    input_linear_velocity_frame: child
    input_topic: /Odometry/healthy
    min_angular_velocity_variance: 0.02
    min_linear_velocity_variance: 0.01
    min_orientation_variance: 0.02
    min_position_variance: 0.01
    output_topic: /mavros/odometry/out
    position_yaw_offset_rad: 0.0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    restamp_message: false
    sensor_to_body_x_m: 0.0
    sensor_to_body_y_m: 0.0
    sensor_to_body_z_m: 0.0
    use_sim_time: false

