set(_AMENT_PACKAGE_NAME "plan_env")
set(plan_env_VERSION "0.0.0")
set(plan_env_MAINTAINER "ma <ma@todo.todo>")
set(plan_env_BUILD_DEPENDS "rclcpp" "rclpy" "std_msgs" "visualization_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "message_filters" "OpenCV" "Eigen3" "PCL" "pcl_conversions")
set(plan_env_BUILDTOOL_DEPENDS "ament_cmake")
set(plan_env_BUILD_EXPORT_DEPENDS "rclcpp" "rclpy" "std_msgs" "visualization_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "message_filters" "OpenCV" "Eigen3" "PCL" "pcl_conversions")
set(plan_env_BUILDTOOL_EXPORT_DEPENDS )
set(plan_env_EXEC_DEPENDS "rclcpp" "rclpy" "std_msgs" "visualization_msgs" "geometry_msgs" "nav_msgs" "cv_bridge" "message_filters" "OpenCV" "Eigen3" "PCL" "pcl_conversions")
set(plan_env_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gtest")
set(plan_env_GROUP_DEPENDS )
set(plan_env_MEMBER_OF_GROUPS )
set(plan_env_DEPRECATED "")
set(plan_env_EXPORT_TAGS)
list(APPEND plan_env_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
