set(_AMENT_PACKAGE_NAME "race_mapping")
set(race_mapping_VERSION "0.0.0")
set(race_mapping_MAINTAINER "utsl <utsl@todo.todo>")
set(race_mapping_BUILD_DEPENDS "rclcpp" "nav_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "libpcl-all-dev")
set(race_mapping_BUILDTOOL_DEPENDS "ament_cmake")
set(race_mapping_BUILD_EXPORT_DEPENDS "rclcpp" "nav_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "libpcl-all-dev")
set(race_mapping_BUILDTOOL_EXPORT_DEPENDS )
set(race_mapping_EXEC_DEPENDS "rclcpp" "nav_msgs" "geometry_msgs" "sensor_msgs" "std_srvs" "std_msgs" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "libpcl-all-dev")
set(race_mapping_TEST_DEPENDS )
set(race_mapping_GROUP_DEPENDS )
set(race_mapping_MEMBER_OF_GROUPS )
set(race_mapping_DEPRECATED "")
set(race_mapping_EXPORT_TAGS)
list(APPEND race_mapping_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
