set(_AMENT_PACKAGE_NAME "race_msgs")
set(race_msgs_VERSION "0.0.0")
set(race_msgs_MAINTAINER "utsl <3334023519@qq.com>")
set(race_msgs_BUILD_DEPENDS "geometry_msgs" "std_msgs")
set(race_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(race_msgs_BUILD_EXPORT_DEPENDS "geometry_msgs" "std_msgs")
set(race_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(race_msgs_EXEC_DEPENDS "rosidl_default_runtime" "geometry_msgs" "std_msgs")
set(race_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(race_msgs_GROUP_DEPENDS )
set(race_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(race_msgs_DEPRECATED "")
set(race_msgs_EXPORT_TAGS)
list(APPEND race_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
