set(_AMENT_PACKAGE_NAME "fastlio_global_slam")
set(fastlio_global_slam_VERSION "0.1.0")
set(fastlio_global_slam_MAINTAINER "robot <robot@example.com>")
set(fastlio_global_slam_BUILD_DEPENDS "Eigen3" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "visualization_msgs")
set(fastlio_global_slam_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(fastlio_global_slam_BUILD_EXPORT_DEPENDS "Eigen3" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "visualization_msgs")
set(fastlio_global_slam_BUILDTOOL_EXPORT_DEPENDS )
set(fastlio_global_slam_EXEC_DEPENDS "launch" "launch_ros" "rosidl_default_runtime" "ros2launch" "Eigen3" "geometry_msgs" "message_filters" "nav_msgs" "pcl_conversions" "rclcpp" "sensor_msgs" "std_msgs" "tf2" "visualization_msgs")
set(fastlio_global_slam_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(fastlio_global_slam_GROUP_DEPENDS )
set(fastlio_global_slam_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(fastlio_global_slam_DEPRECATED "")
set(fastlio_global_slam_EXPORT_TAGS)
list(APPEND fastlio_global_slam_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
