# CMake generated Testfile for 
# Source directory: /home/robot/egohx_ws/26-px4_offboard_control-main/src/fr_lio
# Build directory: /home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_map_correction "/usr/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_results/fr_lio/test_map_correction.gtest.xml" "--package-name" "fr_lio" "--output-file" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/ament_cmake_gtest/test_map_correction.txt" "--command" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_map_correction" "--gtest_output=xml:/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_results/fr_lio/test_map_correction.gtest.xml")
set_tests_properties(test_map_correction PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_map_correction" TIMEOUT "60" WORKING_DIRECTORY "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/robot/egohx_ws/26-px4_offboard_control-main/src/fr_lio/CMakeLists.txt;171;ament_add_gtest;/home/robot/egohx_ws/26-px4_offboard_control-main/src/fr_lio/CMakeLists.txt;0;")
add_test(test_high_rate_odom "/usr/bin/python3" "-u" "/opt/ros/humble/share/ament_cmake_test/cmake/run_test.py" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_results/fr_lio/test_high_rate_odom.gtest.xml" "--package-name" "fr_lio" "--output-file" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/ament_cmake_gtest/test_high_rate_odom.txt" "--command" "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_high_rate_odom" "--gtest_output=xml:/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_results/fr_lio/test_high_rate_odom.gtest.xml")
set_tests_properties(test_high_rate_odom PROPERTIES  LABELS "gtest" REQUIRED_FILES "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio/test_high_rate_odom" TIMEOUT "60" WORKING_DIRECTORY "/home/robot/egohx_ws/26-px4_offboard_control-main/build/fr_lio" _BACKTRACE_TRIPLES "/opt/ros/humble/share/ament_cmake_test/cmake/ament_add_test.cmake;125;add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest_test.cmake;86;ament_add_test;/opt/ros/humble/share/ament_cmake_gtest/cmake/ament_add_gtest.cmake;93;ament_add_gtest_test;/home/robot/egohx_ws/26-px4_offboard_control-main/src/fr_lio/CMakeLists.txt;181;ament_add_gtest;/home/robot/egohx_ws/26-px4_offboard_control-main/src/fr_lio/CMakeLists.txt;0;")
subdirs("third_party/ikd_tree")
subdirs("gtest")
